# Generated by Django 5.1.1 on 2024-10-06 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('M', 'Movie'), ('HM', 'Hollywood Movie'), ('TVS', 'TV Show'), ('Sp', 'Sport')], max_length=100),
        ),
    ]
