# Generated by Django 5.1.1 on 2024-10-06 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0002_alter_movie_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='type',
            field=models.CharField(choices=[('movie', 'movie'), ('Sport', 'Sport'), ('TV Show', 'TV Show')], max_length=100),
        ),
    ]
